# ─────────────────────────────────────────────────────────────────────────────
# ScopeKit — Bootstrap the scoped agent system in any project (PowerShell)
#
# Usage:
#   .\setup.ps1 -ProjectName "My Project"
#   .\setup.ps1                            # defaults to current directory name
#
# What it does:
#   1. Creates the AGENTS/ directory
#   2. Copies MODULE-CHECKLIST.md into AGENTS/
#   3. Copies CLAUDE.md into the project root
#
# Module structure (scopekit.json + MOD-XXX.md briefs) is generated by the AI via
# the scopekit_scaffold tool — it analyzes your import graph. Nothing to hand-count.
# ─────────────────────────────────────────────────────────────────────────────

param(
    [string]$ProjectName = (Split-Path -Leaf (Get-Location))
)

$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$TemplateDir = Join-Path $ScriptDir "..\templates"
$AgentsDir   = "AGENTS"

Write-Host ""
Write-Host "╔══════════════════════════════════════════╗"
Write-Host "║   ScopeKit — Scoped Agent System Setup   ║"
Write-Host "╚══════════════════════════════════════════╝"
Write-Host ""

# ── 1. Create AGENTS/ directory ──────────────────────────────────────────────
New-Item -ItemType Directory -Force -Path $AgentsDir | Out-Null
Write-Host "✓ Created $AgentsDir/"

# ── 2. Copy checklist ─────────────────────────────────────────────────────────
$ChecklistDest = Join-Path $AgentsDir "MODULE-CHECKLIST.md"
if (-not (Test-Path $ChecklistDest)) {
    Copy-Item (Join-Path $TemplateDir "MODULE-CHECKLIST.md") $ChecklistDest
    Write-Host "✓ Copied AGENTS/MODULE-CHECKLIST.md"
}

# ── 3. Copy CLAUDE.md into project root ───────────────────────────────────────
if (-not (Test-Path "CLAUDE.md")) {
    $Claude = (Get-Content (Join-Path $TemplateDir "CLAUDE.md.template") -Raw)
    Set-Content -Path "CLAUDE.md" -Value $Claude -Encoding utf8
    Write-Host "✓ Created CLAUDE.md"
} else {
    Write-Host "⚠  CLAUDE.md already exists — skipping (merge templates/CLAUDE.md.template by hand)"
}

# ── 4. Print next steps ───────────────────────────────────────────────────────
Write-Host ""
Write-Host "-----------------------------------------"
Write-Host " Next steps"
Write-Host "-----------------------------------------"
Write-Host ""
Write-Host "  1. Connect the ScopeKit MCP server AND the enforcement hook to your"
Write-Host "     AI client (see the ScopeKit README for config snippets)."
Write-Host ""
Write-Host "  2. Tell Claude:"
Write-Host '     "Run scopekit_scaffold, then create scopekit.json and the briefs."'
Write-Host ""
Write-Host "     Claude analyzes the import graph, proposes module boundaries,"
Write-Host "     and writes AGENTS/scopekit.json + AGENTS/MOD-XXX.md for you."
Write-Host ""
Write-Host "  3. Run 'scopekit verify' to confirm the briefs match the code."
Write-Host ""
Write-Host "-----------------------------------------"
Write-Host " Done!"
Write-Host "-----------------------------------------"
Write-Host ""
