#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# ScopeKit — Bootstrap the scoped agent system in any project
#
# Usage:
#   ./setup.sh "My Project"
#   ./setup.sh               # defaults to current directory name
#
# What it does:
#   1. Creates the AGENTS/ directory
#   2. Copies MODULE-CHECKLIST.md into AGENTS/
#   3. Copies CLAUDE.md into the project root
#
# Module structure (scopekit.json + MOD-XXX.md briefs) is generated by the AI via
# the scopekit_scaffold tool — it analyzes your import graph. Nothing to hand-count.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="$(cd "$SCRIPT_DIR/../templates" && pwd)"

PROJECT_NAME="${1:-$(basename "$PWD")}"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║   ScopeKit — Scoped Agent System Setup   ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── 1. Create AGENTS/ directory ──────────────────────────────────────────────
mkdir -p AGENTS
echo "✓ Created AGENTS/"

# ── 2. Copy checklist ─────────────────────────────────────────────────────────
CHECKLIST_DEST="AGENTS/MODULE-CHECKLIST.md"
if [ ! -f "$CHECKLIST_DEST" ]; then
  cp "$TEMPLATE_DIR/MODULE-CHECKLIST.md" "$CHECKLIST_DEST"
  echo "✓ Copied AGENTS/MODULE-CHECKLIST.md"
fi

# ── 3. Copy CLAUDE.md into project root ───────────────────────────────────────
if [ ! -f "CLAUDE.md" ]; then
  cp "$TEMPLATE_DIR/CLAUDE.md.template" "CLAUDE.md"
  echo "✓ Created CLAUDE.md"
else
  echo "⚠  CLAUDE.md already exists — skipping (merge templates/CLAUDE.md.template by hand)"
fi

# ── 4. Print next steps ───────────────────────────────────────────────────────
echo ""
echo "─────────────────────────────────────────"
echo " Next steps"
echo "─────────────────────────────────────────"
echo ""
echo "  1. Connect the ScopeKit MCP server AND the enforcement hook to your"
echo "     AI client (see the ScopeKit README for config snippets)."
echo ""
echo "  2. Tell Claude:"
echo '     "Run scopekit_scaffold, then create scopekit.json and the briefs."'
echo ""
echo "     Claude analyzes the import graph, proposes module boundaries,"
echo "     and writes AGENTS/scopekit.json + AGENTS/MOD-XXX.md for you."
echo ""
echo "  3. Run 'scopekit verify' to confirm the briefs match the code."
echo ""
echo "─────────────────────────────────────────"
echo " Done!"
echo "─────────────────────────────────────────"
echo ""
